site_name: Interview Preparation Hub
site_url: https://hcoco1.github.io/blog-mkdocs-material
theme:
  icon:
    repo: fontawesome/brands/github
    logo: material/skull
  name: material
  features:
    - navigation.sections
plugins:
  - blog:
      blog_dir: . 
  - search
  - tags
  - social

nav:
  - index.md
copyright: Copyright &copy; 2024 Ivan Arias
repo_url: https://github.com/hcoco1/blog-mkdocs-material

extra:
  generator: false
