site_name: Interview Preparation Hub
site_url: https://hcoco1.github.io/blog-mkdocs-material
repo_url: https://github.com/hcoco1/blog-mkdocs-material
theme:
  icon:
    repo: fontawesome/brands/github
    logo: material/skull
  name: material
  features:
    - navigation.sections
plugins:
  - blog:
      blog_dir: . 
  - search
  - tags


nav:
  - index.md
copyright: Copyright &copy; 2024 Ivan Arias


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hcoco1
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hcoco1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hcoco1/
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - abbr
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
